name: nvim container build script

on:
  - push:
    branches: [ main ]
  - pull_request:
    branches: [ main ]
  - workflow_dispatch
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "nilsherzig" --password-stdin
        docker image build -t nilsherzig/nvim-container:latest .
        docker push nilsherzig/nvim-container:latest

